apiVersion: v2
name: azure-service-operator
version: v2.0.0-beta.1
description: Deploy components and dependencies of azure-service-operator
home: https://github.com/jadarsie/azure-service-operator/v2
sources:
  - https://github.com/jadarsie/azure-service-operator/v2
