apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    created: "2022-06-28T23:46:30.096765131Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: dffcbf455c912edc7da0771aaebabc40a3e11abec198f226a22ec5871f0b27f6
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.24.tgz
    version: v2.0.0-beta.24
  - apiVersion: v2
    created: "2022-06-28T23:46:30.080798746Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 0d1b19f4647890248aef333bfddd8fd2c203ad492023012d2a53c289edf6c419
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.23.tgz
    version: v2.0.0-beta.23
  - apiVersion: v2
    created: "2022-06-28T23:46:30.041052734Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 8c943f2ef29e8f72c57c9dfa6f2d1c8ebe6676b84efeaff76e66250af9a8d899
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.19.tgz
    version: v2.0.0-beta.19
  - apiVersion: v2
    created: "2022-06-28T23:46:30.02462854Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 4cf9f803d85b6f430bce73cebf4722d4d3057b0e3d11a753d3d14b87b87e8785
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.18.tgz
    version: v2.0.0-beta.18
  - apiVersion: v2
    created: "2022-06-28T23:46:30.007587735Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 058616a7e0f6e40dedf5986813aa999feaf860bdbad00a9acde22d23acd425f4
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.17.tgz
    version: v2.0.0-beta.17
  - apiVersion: v2
    created: "2022-06-28T23:46:29.990428428Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: cbb2ed9dd06cf79a1e2991439d601cff2cce6b580f299911af843a62dfff2d4d
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.16.tgz
    version: v2.0.0-beta.16
  - apiVersion: v2
    created: "2022-06-28T23:46:29.972062499Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 65f26fc06ae048409b8a9a1e25f92b92ee2b92c25b3d251142b449a1186c287a
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.13.tgz
    version: v2.0.0-beta.13
  - apiVersion: v2
    created: "2022-06-28T23:46:29.95479659Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: a553df8c7f515568f73cd695a9d00da70c21e53df49751d9fbaaecae1478cba6
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.12.tgz
    version: v2.0.0-beta.12
  - apiVersion: v2
    created: "2022-06-28T23:46:29.938185893Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: cb3ef50d20ee6d913e8c9a899b6081f500a62f3917edde82f26aa95f5d3aae27
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.11.tgz
    version: v2.0.0-beta.11
  - apiVersion: v2
    created: "2022-06-28T23:46:30.234612299Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 182a88d3bb8c8bc33ccf9d4736c806cd8028aea7205cd44b30ee2a1d6031af86
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.9.tgz
    version: v2.0.0-beta.9
  - apiVersion: v2
    created: "2022-06-28T23:46:30.218143304Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 0e8ef31d7cc142f60dcad8010715908f06352f9af51a0a4aa443d3740cd32efc
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.8.tgz
    version: v2.0.0-beta.8
  - apiVersion: v2
    created: "2022-06-28T23:46:30.199828076Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: f72e36062ccaba9c9312afb266c207413b8cdab4f4cd9e8a56a10e18f87f32b4
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.7.tgz
    version: v2.0.0-beta.7
  - apiVersion: v2
    created: "2022-06-28T23:46:30.183623586Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: a6d4c150490a1c463df8c028fa41d4bff8f42509a61b725e71f9ced42083bbd0
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.6.tgz
    version: v2.0.0-beta.6
  - apiVersion: v2
    created: "2022-06-28T23:46:30.160238767Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 4e29b39e83366b87fb5edf11edb6ba694033cde5f3d2b2b8b4b8f79121545887
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.5.tgz
    version: v2.0.0-beta.5
  - apiVersion: v2
    created: "2022-06-28T23:46:30.137426059Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 284644e43bc924ec05fe77cfeeb79f1bbb4cf1866310c7e5f2cdc57e771e8082
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.4.tgz
    version: v2.0.0-beta.4
  - apiVersion: v2
    created: "2022-06-28T23:46:30.12071776Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: baa948a31a85c99887b8374262206400d85735f269a49e0ccb50cee16bddf455
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.3.tgz
    version: v2.0.0-beta.3
  - apiVersion: v2
    created: "2022-06-28T23:46:30.063961744Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 54388ccf2c4811fb6efd2a7823292d259812a5373721d140a96afa0511ef3d76
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.2.tgz
    version: v2.0.0-beta.2
  - apiVersion: v2
    created: "2022-06-28T23:46:29.920263672Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 5e94b175024b9da65a34dff0d27ed456744f306344e78fd4b294435e82c20187
    home: https://github.com/jadarsie/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/jadarsie/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.1.tgz
    version: v2.0.0-beta.1
  - apiVersion: v2
    created: "2022-06-28T23:46:29.895343526Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 644b1f9e38f7cd868963e52dc449cbb16231c10b3ee0ba303e864f1a392444fb
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-alpha.6.tgz
    version: v2.0.0-alpha.6
generated: "2022-06-28T23:46:29.876477389Z"
