apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    created: "2022-04-24T06:39:34.964963979Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: f34490d6fa691665acdcde5212ed9457a6251d59472ba0b322fd1f4ebabfcebb
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.1.tgz
    version: v2.0.0-beta.1
  - apiVersion: v2
    created: "2022-04-24T06:39:34.944800523Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 6359f0a08170fef88e5d08366c9c27db71e17310d87436a54d61eb1ea97a561a
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-beta.0.tgz
    version: v2.0.0-beta.0
  - apiVersion: v2
    created: "2022-04-24T06:39:34.924122763Z"
    description: Deploy components and dependencies of azure-service-operator
    digest: 644b1f9e38f7cd868963e52dc449cbb16231c10b3ee0ba303e864f1a392444fb
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0-alpha.6.tgz
    version: v2.0.0-alpha.6
generated: "2022-04-24T06:39:34.909832252Z"
