apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: azureserviceoperator-manager-role
rules:
- apiGroups:
  - authorization.azure.com
  resources:
  - roleassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.azure.com
  resources:
  - roleassignments/finalizers
  - roleassignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.azure.com
  resources:
  - batchaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.azure.com
  resources:
  - batchaccounts/finalizers
  - batchaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.azure.com
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.azure.com
  resources:
  - redis/finalizers
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.azure.com
  resources:
  - redisenterprisedatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.azure.com
  resources:
  - redisenterprisedatabases/finalizers
  - redisenterprisedatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.azure.com
  resources:
  - redisenterprises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.azure.com
  resources:
  - redisenterprises/finalizers
  - redisenterprises/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.azure.com
  resources:
  - redisfirewallrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.azure.com
  resources:
  - redisfirewallrules/finalizers
  - redisfirewallrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.azure.com
  resources:
  - redislinkedservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.azure.com
  resources:
  - redislinkedservers/finalizers
  - redislinkedservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.azure.com
  resources:
  - redispatchschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.azure.com
  resources:
  - redispatchschedules/finalizers
  - redispatchschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.azure.com
  resources:
  - disks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.azure.com
  resources:
  - disks/finalizers
  - disks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.azure.com
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.azure.com
  resources:
  - images/finalizers
  - images/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.azure.com
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.azure.com
  resources:
  - snapshots/finalizers
  - snapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.azure.com
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.azure.com
  resources:
  - virtualmachines/finalizers
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.azure.com
  resources:
  - virtualmachinescalesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.azure.com
  resources:
  - virtualmachinescalesets/finalizers
  - virtualmachinescalesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - containerregistry.azure.com
  resources:
  - registries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containerregistry.azure.com
  resources:
  - registries/finalizers
  - registries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - containerservice.azure.com
  resources:
  - managedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containerservice.azure.com
  resources:
  - managedclusters/finalizers
  - managedclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - containerservice.azure.com
  resources:
  - managedclustersagentpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containerservice.azure.com
  resources:
  - managedclustersagentpools/finalizers
  - managedclustersagentpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - eventgrid.azure.com
  resources:
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventgrid.azure.com
  resources:
  - domains/finalizers
  - domains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eventgrid.azure.com
  resources:
  - domainstopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventgrid.azure.com
  resources:
  - domainstopics/finalizers
  - domainstopics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eventgrid.azure.com
  resources:
  - eventsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventgrid.azure.com
  resources:
  - eventsubscriptions/finalizers
  - eventsubscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eventgrid.azure.com
  resources:
  - topics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventgrid.azure.com
  resources:
  - topics/finalizers
  - topics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - insights.azure.com
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insights.azure.com
  resources:
  - components/finalizers
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - insights.azure.com
  resources:
  - webtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insights.azure.com
  resources:
  - webtests/finalizers
  - webtests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - managedidentity.azure.com
  resources:
  - userassignedidentities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managedidentity.azure.com
  resources:
  - userassignedidentities/finalizers
  - userassignedidentities/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - loadbalancers/finalizers
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - networkinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - networkinterfaces/finalizers
  - networkinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - networksecuritygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - networksecuritygroups/finalizers
  - networksecuritygroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - networksecuritygroupssecurityrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - networksecuritygroupssecurityrules/finalizers
  - networksecuritygroupssecurityrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - publicipaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - publicipaddresses/finalizers
  - publicipaddresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworkgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworkgateways/finalizers
  - virtualnetworkgateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworks/finalizers
  - virtualnetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworkssubnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworkssubnets/finalizers
  - virtualnetworkssubnets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworksvirtualnetworkpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - virtualnetworksvirtualnetworkpeerings/finalizers
  - virtualnetworksvirtualnetworkpeerings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operationalinsights.azure.com
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operationalinsights.azure.com
  resources:
  - workspaces/finalizers
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resources.azure.com
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.azure.com
  resources:
  - resourcegroups/finalizers
  - resourcegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - signalrservice.azure.com
  resources:
  - signalrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - signalrservice.azure.com
  resources:
  - signalrs/finalizers
  - signalrs/status
  verbs:
  - get
  - patch
  - update
